export const GET_ORDERS_LOADING = 'GET_ORDERS_LOADING';
export const GET_ORDERS_SUCCESS = 'GET_ORDERS_SUCCESS';
export const GET_ORDERS_FAIL = 'GET_ORDERS_FAIL';

export const ADD_ORDER_LOADING = 'ADD_ORDER_LOADING';
export const ADD_ORDER_SUCCESS = 'ADD_ORDER_SUCCESS';
export const ADD_ORDER_FAIL = 'ADD_ORDER_FAIL';

export const EDIT_ORDER_LOADING = 'EDIT_ORDER_LOADING';
export const EDIT_ORDER_SUCCESS = 'EDIT_ORDER_SUCCESS';
export const EDIT_ORDER_FAIL = 'EDIT_ORDER_FAIL';

export const DELETE_ORDER_LOADING = 'DELETE_ORDER_LOADING';
export const DELETE_ORDER_SUCCESS = 'DELETE_ORDER_SUCCESS';
export const DELETE_ORDER_FAIL = 'DELETE_ORDER_FAIL';

export const SEND_ORDER_LOADING = 'SEND_ORDER_LOADING';
export const SEND_ORDER_SUCCESS = 'SEND_ORDER_SUCCESS';
export const SEND_ORDER_FAIL = 'SEND_ORDER_FAIL';

export const ORDER_PAY_LOADING = 'ORDER_PAY_LOADING';
export const ORDER_PAY_SUCCESS = 'ORDER_PAY_SUCCESS';
export const ORDER_PAY_FAIL = 'ORDER_PAY_FAIL';

export const GET_ORDERITEMS_LOADING = 'GET_ORDERITEMS_LOADING';
export const GET_ORDERITEMS_SUCCESS = 'GET_ORDERITEMS_SUCCESS';
export const GET_ORDERITEMS_FAIL = 'GET_ORDERITEMS_FAIL';

export const ADD_ORDERITEM_LOADING = 'ADD_ORDERITEM_LOADING';
export const ADD_ORDERITEM_SUCCESS = 'ADD_ORDERITEM_SUCCESS';
export const ADD_ORDERITEM_FAIL = 'ADD_ORDERITEM_FAIL';

export const EDIT_ORDERITEM_LOADING = 'EDIT_ORDERITEM_LOADING';
export const EDIT_ORDERITEM_SUCCESS = 'EDIT_ORDERITEM_SUCCESS';
export const EDIT_ORDERITEM_FAIL = 'EDIT_ORDERITEM_FAIL';

export const DELETE_ORDERITEM_LOADING = 'DELETE_ORDERITEM_LOADING';
export const DELETE_ORDERITEM_SUCCESS = 'DELETE_ORDERITEM_SUCCESS';
export const DELETE_ORDERITEM_FAIL = 'DELETE_ORDERITEM_FAIL';

export const PHONENUMBER_SIGNIN_SUBMIT_LOADING =
  'PHONENUMBER_SIGNIN_SUBMIT_LOADING';
export const PHONENUMBER_SIGNIN_SUBMIT_SUCCESS =
  'PHONENUMBER_SIGNIN_SUBMIT_SUCCESS';
export const PHONENUMBER_SIGNIN_SUBMIT_FAIL = 'PHONENUMBER_SIGNIN_SUBMIT_FAIL';

export const PHONENUMBER_OTP_SUBMIT_LOADING = 'PHONENUMBER_OTP_SUBMIT_LOADING';
export const PHONENUMBER_OTP_SUBMIT_SUCCESS = 'PHONENUMBER_OTP_SUBMIT_SUCCESS';
export const PHONENUMBER_OTP_SUBMIT_FAIL = 'PHONENUMBER_OTP_SUBMIT_FAIL';

export const LOGOUT_LOADING = 'LOGOUT_LOADING';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';

export const CRED_UPDATE_LOADING = 'CRED_UPDATE_LOADING';
export const CRED_UPDATE_SUCCESS = 'CRED_UPDATE_SUCCESS';
export const CRED_UPDATE_FAIL = 'CRED_UPDATE_FAIL';

export const USER_NAME_UPDATE_LOADING = 'USER_NAME_UPDATE_LOADING';
export const USER_NAME_UPDATE_SUCCESS = 'USER_NAME_UPDATE_SUCCESS';
export const USER_NAME_UPDATE_FAIL = 'USER_NAME_UPDATE_FAIL';

export const GET_USER_DETAILS_LOADING = 'GET_USER_DETAILS_LOADING';
export const GET_USER_DETAILS_SUCCESS = 'GET_USER_DETAILS_SUCCESS';
export const GET_USER_DETAILS_FAIL = 'GET_USER_DETAILS_FAIL';

export const USER_ADDRESS_UPDATE_LOADING = 'USER_ADDRESS_UPDATE_LOADING';
export const USER_ADDRESS_UPDATE_SUCCESS = 'USER_ADDRESS_UPDATE_SUCCESS';
export const USER_ADDRESS_UPDATE_FAIL = 'USER_ADDRESS_UPDATE_FAIL';

export const GET_STORES_LOADING = 'GET_STORES_LOADING';
export const GET_STORES_SUCCESS = 'GET_STORES_SUCCESS';
export const GET_STORES_FAIL = 'GET_STORES_FAIL';
